<template>
  <div
      v-editable="blok"
      class="heroSec lg:w-9/12 md:w-10/12 w-11/12 text-center my-0 md:my-10 md:flex justify-center m-auto"
  >
    <div class="lg:w-1/2 md:w-1/2 w-100vw px-3 lg:pl-10 lg:pr-16 sm:pb-0 pb-12 ">
      <nuxtImg :src="blok.portrait_image.filename"
               :alt="blok.portrait_image.alt"
               format="webp"
               quality="50"
               width="400px"
               loading="eager"
               priority
               class="claudiasPortrait justify-self-center rounded-full"
      />
    </div>

    <div class="textSec lg:w-1/2 md:w-1/2 w-100vw lg:pl-8 lg:pr-4 md:px-8 lg:py-4 md:py-4 px-3 py-1 self-center">
      <h1  class="welcomeTitle lg:text-6xl md:text-4xl text-5xl text-white font-bold uppercase text-focus-in tracking-wide text-left">
        Hello<br> I'm <span id="gradient">Claudia</span>
      </h1>
      <div v-html="textdesc" class="welcomeDesc text-white text-base align-self-end text-justify py-5"></div>
    </div>
  </div>
</template>

<script setup>
import { defineProps, computed } from 'vue';
import { renderRichText } from '@storyblok/vue';

const props = defineProps({
  blok: {
    type: Object,
    required: true
  }
});

const textdesc = computed(() => {
    return renderRichText(props.blok.hero_text);
});
</script>

<style scoped>
.heroSec{
  padding: 44px 0;
}
.welcomeTitle {
  font-family: "Vidaloka", serif;
  font-weight: 400;
  font-style: normal;
  text-shadow: 2px 2px 4px rgba(63, 36, 36, 0.48);
}

@media (min-width: 1000px) and(max-width: 1024px){
  .textSec{
    h1{
      font-size: 2.75rem;
    }
  }
}


.text-focus-in {
  animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

#gradient {
  color: transparent;
  background: linear-gradient(to left, #19AFE1, #C0598E, #c0387e, #19AFE1);
  background-size: 1000px 100%;
  animation: bg 25s linear infinite;
  background-clip: text;
  -webkit-background-clip: text;
}
@keyframes bg {
  0% {
    background-position-x: 0;
  }
  100% {
    background-position-x: 10000px;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-5-31 22:46:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes text-focus-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0px);
    opacity: 1;
  }
}


</style>
