<template>
  <div
      v-editable="blok"
      class="w-full bg-[#080502] text-center parent mb-8"
  >
    <img :src="blok.background_image.filename" alt="Abstract Background Image" class="backgroundImg bg-contain w-full min-h-[300px] md:max-h-[400px] opacity-30 z-0 "/>

    <img :src="blok.portrait_image.filename"
         data-aos="fade-up"
         alt="Portrait of myself "
         class="claudiasPortrait justify-self-center max-h-[400px] max-w-[80vw] z-10"/>


    <h1  class="welcomeTitle text-4xl text-[#FBF7F3] mt-12 justify-self-center align-self-center z-20 font-bold uppercase text-focus-in -mb-5 tracking-wide">
      {{blok.title}}
    </h1>

    <div v-html="textdesc" class="welcomeDesc text-[#FBF7F3] text-base align-self-end text-justify z-20 mt-4 md:-mt-5 px-8 mb-6  md:px-16"></div>


  </div>
</template>

<script setup>
import { defineProps, computed } from 'vue';
import { renderRichText } from '@storyblok/vue';

const props = defineProps({
  blok: {
    type: Object,
    required: true
  }
});

const textdesc = computed(() => {
    return renderRichText(props.blok.hero_text);
});
</script>

<style scoped>

.parent {
  display: grid;
  grid-template-columns: repeat(auto-fit, 1fr);
  grid-template-rows: repeat(auto-fit, 1fr);
}

.backgroundImg {
  grid-area: 1 / 1 / 4 / 6;
}
.claudiasPortrait {
  grid-area: 2 / 2 / 5 / 5;
  box-shadow: 5px 6px 8px 2px rgba(0,0,0,0.25);
}
.welcomeTitle {
  grid-area: 1 / 2 / 2 / 5;

  font-family: "Vidaloka", serif;
  font-weight: 400;
  font-style: normal;
  text-shadow: 2px 2px 4px rgba(63, 36, 36, 0.48);
}
.welcomeDesc {
  grid-area: 5 / 2 / 6 / 5;
}


.text-focus-in {
  animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}


/* ----------------------------------------------
 * Generated by Animista on 2024-5-31 22:46:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
@keyframes text-focus-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0px);
    opacity: 1;
  }
}


</style>

<style scoped>

</style>
