<template>
  <div
      v-editable="blok"
      class="w-full bg-[#120A03] text-center parent"
  >
    <img :src="blok.background_image.filename" alt="Portrait" class="cover div1 w-full max-h-[400px] opacity-30 z-0 "/>

    <img :src="blok.portrait_image.filename" alt="Portrait " class="div2 max-h-[400px] z-10 scale-up-ver-top"/>


    <div  class="text-4xl text-[#FBF7F3] mb-4 div3 z-20 font-bold text-focus-in">
      {{blok.title}}
    </div>
    <div  class="text-xl text-[#FBF7F3] mb-4 div4 z-20">
      {{blok.hero_text}}
    </div>


  </div>
</template>

<script setup>
defineProps(
    { blok: Object } //sagt nuxt, dass storyblok objekt mitgegeben wird
);
</script>

<style scoped>

.parent {
  display: grid;
  grid-template-columns: repeat(auto-fill, 1fr);
  grid-template-rows: repeat(auto-fill, 1fr);
  grid-column-gap: 0px;
  grid-row-gap: 0px;
}

.div1 {
  grid-area: 1 / 1 / 4 / 6;
}
.div2 {
  grid-area: 2 / 2 / 5 / 5;
  justify-self: center;
  box-shadow: 5px 6px 8px 2px rgba(0,0,0,0.25);
}
.div3 {
  grid-area: 1 / 2 / 2 / 5;
  justify-self: center;
  align-self: center;


 /* font-family: "Petit Formal Script", cursive;
  font-weight: 400;
  font-style: normal;*/

  font-family: "Vidaloka", serif;
  font-weight: 400;
  font-style: normal;
}
.div4 {
  grid-area: 5 / 2 / 6 / 5;
  align-self: end;
}
/*
@media(max-width: 770px) {
  .parent {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    grid-template-rows: repeat(4, 1fr);
    grid-column-gap: 0px;
    grid-row-gap: 0px;
  }

  .div1 { grid-area: 1 / 1 / 5 / 6; }
  .div2 {
    grid-area: 1 / 2 / 4 / 5;
    align-self: end;
    margin-bottom: 20px;
  }
  .div3 { grid-area: 1 / 2 / 2 / 5; }
  .div4 { grid-area: 4 / 2 / 5 / 5; }

}

@media(max-width: 660px) {
  .parent {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    grid-template-rows: repeat(3, 1fr);
    grid-column-gap: 0px;
    grid-row-gap: 0px;
  }

  .div1 { grid-area: 1 / 1 / 5 / 6; }
  .div2 {
    grid-area: 1 / 2 / 4 / 4;
    align-self: center;
  }
  .div3 { grid-area: 1 / 2 / 2 / 4; }
  .div4 {
    margin-top: 50px;
    align-self: end;
    grid-area: 3 / 2 / 4 / 4;
  }

}

@media(max-width: 600px) {
  .parent {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: repeat(3, 1fr);
    grid-column-gap: 0px;
    grid-row-gap: 0px;
  }

  .div1 { grid-area: 1 / 1 / 4 / 2; }
  .div2 { grid-area: 1 / 1 / 4 / 2; }
  .div3 {
    grid-area: 1 / 1 / 2 / 2;
    align-self: start;
  }
  .div4 {
    grid-area: 3 / 1 / 4 / 2;
    align-self: start;
    margin: 10px;
  }


}*/


  .scale-up-ver-top {
  animation: scale-up-ver-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-5-31 22:45:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-ver-top
 * ----------------------------------------
 */
@keyframes scale-up-ver-top {
  0% {
    transform: scaleY(0.4);
    transform-origin: 100% 0%;
  }
  100% {
    transform: scaleY(1);
    transform-origin: 100% 0%;
  }
}



.text-focus-in {
  animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}


/* ----------------------------------------------
 * Generated by Animista on 2024-5-31 22:46:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@keyframes text-focus-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0px);
    opacity: 1;
  }
}





</style>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Petit+Formal+Script&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Vidaloka&display=swap');

h2 {
  font-family: 'Abril Fatface', sans-serif;
}
</style>
